print ("####################################")
print ("#                                  #")
print ("#  Muhammad Rasyha Irsach Warafah  #")
print ("#         2510817210016            #")
print ("#                                  #")
print ("####################################")